### ISSUE TITLE
Switch jump table is treated as part of the function

### ISSUE THREAD

**Issue by Predelnik** [diasurgical/devilution-comparer#16]
I don't know if it's related to #11 and/or deficiency of pdb but seems like `switch` jump table is added to diff and also incorrectly parsed as a code. You can easily test it on `OperateObject` function:
![image](https://user-images.githubusercontent.com/2133957/56476532-06054900-64a2-11e9-9be7-7519b82b65fc.png)

**Comment by AJenbo** [comment]
Switching to .map might solve it. I looked into .map recently build couldn't find any tool that was willing to parse the function names, but they actually seem to be easy to parse so maybe we could write our own function for it.

**Comment by seritools** [comment]
I don't think switching to .map will solve it - the map files don't include any function size info, and if they did, it would probably be the same as the pdb one. I'd rather argue that the comparer-config.toml should include the jump table as well, since it's technically a part of the function :)

Display-wise, this could definitely be improved though.

Dunno if y'all seen it, but I've started working on a more general tool for comparisons: https://github.com/seritools/bin-exact
In there it'll be much easier to add multiple sources like pdb, map, toml, etc., which can be configured and used separately as well.

**Comment by seritools** [comment]
In the current stage of the devilution project it's fixed/circumvented by https://github.com/diasurgical/devilution-comparer/releases/tag/v0.4.0, so closing for now :)
